<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Brepia.Grasshopper/Brepia.Grasshopper.csproj" />
    <PackageReference Include="RhinoCommon" Version="8.34.26223.11001" />
    <PackageReference Include="Grasshopper" Version="8.34.26223.11001" />
  </ItemGroup>
</Project>
