/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LayoutRouteImport } from './routes/_layout';
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email';
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as SigninRouteImport } from './routes/signin';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as SignupEmailRouteImport } from './routes/signup-email';
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service';
import { Route as UpdatePasswordRouteImport } from './routes/update-password';
import { Route as LayoutIndexRouteImport } from './routes/_layout/index';
import { Route as LayoutSplatRouteImport } from './routes/_layout/$';
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth';
import { Route as ApiCreativeChatRouteImport } from './routes/api/creative-chat';
import { Route as ApiDeleteUserRouteImport } from './routes/api/delete-user';
import { Route as ApiFalWebhookRouteImport } from './routes/api/fal-webhook';
import { Route as ApiMeshRouteImport } from './routes/api/mesh';
import { Route as ApiParametricChatRouteImport } from './routes/api/parametric-chat';
import { Route as ApiTitleGeneratorRouteImport } from './routes/api/title-generator';
import { Route as AssetsSplatRouteImport } from './routes/assets.$';
import { Route as LayoutAuthAppRouteImport } from './routes/_layout/_auth/app';
import { Route as LayoutAuthBrepRouteImport } from './routes/_layout/_auth/brep';
import { Route as LayoutAuthHistoryRouteImport } from './routes/_layout/_auth/history';
import { Route as LayoutAuthSettingsRouteImport } from './routes/_layout/_auth/settings';
import { Route as LayoutShareIdRouteImport } from './routes/_layout/share/$id';
import { Route as ApiAiSettingsPreferencesRouteImport } from './routes/api/ai-settings/preferences';
import { Route as ApiAiSettingsProfilesRouteImport } from './routes/api/ai-settings/profiles';
import { Route as ApiAiSettingsProvidersRouteImport } from './routes/api/ai-settings/providers';
import { Route as ApiBrepEvaluateRouteImport } from './routes/api/brep/evaluate';
import { Route as ApiConversationsDeleteRouteImport } from './routes/api/conversations/delete';
import { Route as ApiConversationsWorkspaceRouteImport } from './routes/api/conversations/workspace';
import { Route as ApiExportStepRouteImport } from './routes/api/export.step';
import { Route as ApiJacksonPollockSplatRouteImport } from './routes/api/jackson-pollock/$';
import { Route as ApiModelsCatalogRouteImport } from './routes/api/models/catalog';
import { Route as ApiOpencodeModelsRouteImport } from './routes/api/opencode/models';
import { Route as ApiScadImportGithubRouteImport } from './routes/api/scad-import.github';
import { Route as ApiSettingsAdminModelsRouteImport } from './routes/api/settings/adminModels';
import { Route as ApiSettingsInstanceIdentityRouteImport } from './routes/api/settings/instanceIdentity';
import { Route as ApiSettingsRuntimeIntegrationsRouteImport } from './routes/api/settings/runtimeIntegrations';
import { Route as LayoutAuthBrepIndexRouteImport } from './routes/_layout/_auth/brep/index';
import { Route as LayoutAuthBrepIdRouteImport } from './routes/_layout/_auth/brep/$id';
import { Route as LayoutAuthEditorIdRouteImport } from './routes/_layout/_auth/editor/$id';
import { Route as LayoutAuthProjectIdRouteImport } from './routes/_layout/_auth/project/$id';
import { Route as ApiAiSettingsProfilesProfileIdRouteImport } from './routes/api/ai-settings/profiles/$profileId';
import { Route as ApiAiSettingsProvidersProviderIdRouteImport } from './routes/api/ai-settings/providers/$providerId';
import { Route as ApiAiSettingsProvidersBuiltinsRouteImport } from './routes/api/ai-settings/providers/builtins';
import { Route as ApiAiSettingsProvidersTestRouteImport } from './routes/api/ai-settings/providers/test';
import { Route as ApiBrepExportGrasshopperPlanRouteImport } from './routes/api/brep/export.grasshopper-plan';
import { Route as ApiBrepExportStepRouteImport } from './routes/api/brep/export.step';
import { Route as ApiInternalAccountDeleteRouteImport } from './routes/api/internal/account/delete';
import { Route as ApiModelsCatalogAllRouteImport } from './routes/api/models/catalog/all';
import { Route as ApiAiSettingsProvidersProviderIdModelsRouteImport } from './routes/api/ai-settings/providers/$providerId/models';
import { Route as ApiAiSettingsProvidersProviderIdModelsModelIdRouteImport } from './routes/api/ai-settings/providers/$providerId/models/$modelId';

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const SignupEmailRoute = SignupEmailRouteImport.update({
  id: '/signup-email',
  path: '/signup-email',
  getParentRoute: () => rootRouteImport,
} as any);
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any);
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutSplatRoute = LayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LayoutRoute,
} as any);
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any);
const ApiCreativeChatRoute = ApiCreativeChatRouteImport.update({
  id: '/api/creative-chat',
  path: '/api/creative-chat',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiDeleteUserRoute = ApiDeleteUserRouteImport.update({
  id: '/api/delete-user',
  path: '/api/delete-user',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiFalWebhookRoute = ApiFalWebhookRouteImport.update({
  id: '/api/fal-webhook',
  path: '/api/fal-webhook',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMeshRoute = ApiMeshRouteImport.update({
  id: '/api/mesh',
  path: '/api/mesh',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiParametricChatRoute = ApiParametricChatRouteImport.update({
  id: '/api/parametric-chat',
  path: '/api/parametric-chat',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTitleGeneratorRoute = ApiTitleGeneratorRouteImport.update({
  id: '/api/title-generator',
  path: '/api/title-generator',
  getParentRoute: () => rootRouteImport,
} as any);
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutAuthAppRoute = LayoutAuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutAuthBrepRoute = LayoutAuthBrepRouteImport.update({
  id: '/brep',
  path: '/brep',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutAuthHistoryRoute = LayoutAuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutAuthSettingsRoute = LayoutAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutShareIdRoute = LayoutShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => LayoutRoute,
} as any);
const ApiAiSettingsPreferencesRoute =
  ApiAiSettingsPreferencesRouteImport.update({
    id: '/api/ai-settings/preferences',
    path: '/api/ai-settings/preferences',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAiSettingsProfilesRoute = ApiAiSettingsProfilesRouteImport.update({
  id: '/api/ai-settings/profiles',
  path: '/api/ai-settings/profiles',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAiSettingsProvidersRoute = ApiAiSettingsProvidersRouteImport.update({
  id: '/api/ai-settings/providers',
  path: '/api/ai-settings/providers',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBrepEvaluateRoute = ApiBrepEvaluateRouteImport.update({
  id: '/api/brep/evaluate',
  path: '/api/brep/evaluate',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiConversationsDeleteRoute = ApiConversationsDeleteRouteImport.update({
  id: '/api/conversations/delete',
  path: '/api/conversations/delete',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiConversationsWorkspaceRoute =
  ApiConversationsWorkspaceRouteImport.update({
    id: '/api/conversations/workspace',
    path: '/api/conversations/workspace',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiExportStepRoute = ApiExportStepRouteImport.update({
  id: '/api/export/step',
  path: '/api/export/step',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiJacksonPollockSplatRoute = ApiJacksonPollockSplatRouteImport.update({
  id: '/api/jackson-pollock/$',
  path: '/api/jackson-pollock/$',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiModelsCatalogRoute = ApiModelsCatalogRouteImport.update({
  id: '/api/models/catalog',
  path: '/api/models/catalog',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOpencodeModelsRoute = ApiOpencodeModelsRouteImport.update({
  id: '/api/opencode/models',
  path: '/api/opencode/models',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiScadImportGithubRoute = ApiScadImportGithubRouteImport.update({
  id: '/api/scad-import/github',
  path: '/api/scad-import/github',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSettingsAdminModelsRoute = ApiSettingsAdminModelsRouteImport.update({
  id: '/api/settings/adminModels',
  path: '/api/settings/adminModels',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSettingsInstanceIdentityRoute =
  ApiSettingsInstanceIdentityRouteImport.update({
    id: '/api/settings/instanceIdentity',
    path: '/api/settings/instanceIdentity',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiSettingsRuntimeIntegrationsRoute =
  ApiSettingsRuntimeIntegrationsRouteImport.update({
    id: '/api/settings/runtimeIntegrations',
    path: '/api/settings/runtimeIntegrations',
    getParentRoute: () => rootRouteImport,
  } as any);
const LayoutAuthBrepIndexRoute = LayoutAuthBrepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAuthBrepRoute,
} as any);
const LayoutAuthBrepIdRoute = LayoutAuthBrepIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutAuthBrepRoute,
} as any);
const LayoutAuthEditorIdRoute = LayoutAuthEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const LayoutAuthProjectIdRoute = LayoutAuthProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => LayoutAuthRoute,
} as any);
const ApiAiSettingsProfilesProfileIdRoute =
  ApiAiSettingsProfilesProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => ApiAiSettingsProfilesRoute,
  } as any);
const ApiAiSettingsProvidersProviderIdRoute =
  ApiAiSettingsProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => ApiAiSettingsProvidersRoute,
  } as any);
const ApiAiSettingsProvidersBuiltinsRoute =
  ApiAiSettingsProvidersBuiltinsRouteImport.update({
    id: '/builtins',
    path: '/builtins',
    getParentRoute: () => ApiAiSettingsProvidersRoute,
  } as any);
const ApiAiSettingsProvidersTestRoute =
  ApiAiSettingsProvidersTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => ApiAiSettingsProvidersRoute,
  } as any);
const ApiBrepExportGrasshopperPlanRoute =
  ApiBrepExportGrasshopperPlanRouteImport.update({
    id: '/api/brep/export/grasshopper-plan',
    path: '/api/brep/export/grasshopper-plan',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiBrepExportStepRoute = ApiBrepExportStepRouteImport.update({
  id: '/api/brep/export/step',
  path: '/api/brep/export/step',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiInternalAccountDeleteRoute =
  ApiInternalAccountDeleteRouteImport.update({
    id: '/api/internal/account/delete',
    path: '/api/internal/account/delete',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiModelsCatalogAllRoute = ApiModelsCatalogAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ApiModelsCatalogRoute,
} as any);
const ApiAiSettingsProvidersProviderIdModelsRoute =
  ApiAiSettingsProvidersProviderIdModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => ApiAiSettingsProvidersProviderIdRoute,
  } as any);
const ApiAiSettingsProvidersProviderIdModelsModelIdRoute =
  ApiAiSettingsProvidersProviderIdModelsModelIdRouteImport.update({
    id: '/$modelId',
    path: '/$modelId',
    getParentRoute: () => ApiAiSettingsProvidersProviderIdModelsRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/signin': typeof SigninRoute;
  '/signup': typeof SignupRoute;
  '/signup-email': typeof SignupEmailRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/update-password': typeof UpdatePasswordRoute;
  '/$': typeof LayoutSplatRoute;
  '/api/creative-chat': typeof ApiCreativeChatRoute;
  '/api/delete-user': typeof ApiDeleteUserRoute;
  '/api/fal-webhook': typeof ApiFalWebhookRoute;
  '/api/mesh': typeof ApiMeshRoute;
  '/api/parametric-chat': typeof ApiParametricChatRoute;
  '/api/title-generator': typeof ApiTitleGeneratorRoute;
  '/assets/$': typeof AssetsSplatRoute;
  '/app': typeof LayoutAuthAppRoute;
  '/brep': typeof LayoutAuthBrepRouteWithChildren;
  '/history': typeof LayoutAuthHistoryRoute;
  '/settings': typeof LayoutAuthSettingsRoute;
  '/share/$id': typeof LayoutShareIdRoute;
  '/api/ai-settings/preferences': typeof ApiAiSettingsPreferencesRoute;
  '/api/ai-settings/profiles': typeof ApiAiSettingsProfilesRouteWithChildren;
  '/api/ai-settings/providers': typeof ApiAiSettingsProvidersRouteWithChildren;
  '/api/brep/evaluate': typeof ApiBrepEvaluateRoute;
  '/api/conversations/delete': typeof ApiConversationsDeleteRoute;
  '/api/conversations/workspace': typeof ApiConversationsWorkspaceRoute;
  '/api/export/step': typeof ApiExportStepRoute;
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute;
  '/api/models/catalog': typeof ApiModelsCatalogRouteWithChildren;
  '/api/opencode/models': typeof ApiOpencodeModelsRoute;
  '/api/scad-import/github': typeof ApiScadImportGithubRoute;
  '/api/settings/adminModels': typeof ApiSettingsAdminModelsRoute;
  '/api/settings/instanceIdentity': typeof ApiSettingsInstanceIdentityRoute;
  '/api/settings/runtimeIntegrations': typeof ApiSettingsRuntimeIntegrationsRoute;
  '/brep/$id': typeof LayoutAuthBrepIdRoute;
  '/editor/$id': typeof LayoutAuthEditorIdRoute;
  '/project/$id': typeof LayoutAuthProjectIdRoute;
  '/api/ai-settings/profiles/$profileId': typeof ApiAiSettingsProfilesProfileIdRoute;
  '/api/ai-settings/providers/$providerId': typeof ApiAiSettingsProvidersProviderIdRouteWithChildren;
  '/api/ai-settings/providers/builtins': typeof ApiAiSettingsProvidersBuiltinsRoute;
  '/api/ai-settings/providers/test': typeof ApiAiSettingsProvidersTestRoute;
  '/api/brep/export/grasshopper-plan': typeof ApiBrepExportGrasshopperPlanRoute;
  '/api/brep/export/step': typeof ApiBrepExportStepRoute;
  '/api/internal/account/delete': typeof ApiInternalAccountDeleteRoute;
  '/api/models/catalog/all': typeof ApiModelsCatalogAllRoute;
  '/brep/': typeof LayoutAuthBrepIndexRoute;
  '/api/ai-settings/providers/$providerId/models': typeof ApiAiSettingsProvidersProviderIdModelsRouteWithChildren;
  '/api/ai-settings/providers/$providerId/models/$modelId': typeof ApiAiSettingsProvidersProviderIdModelsModelIdRoute;
}
export interface FileRoutesByTo {
  '/confirm-email': typeof ConfirmEmailRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/signin': typeof SigninRoute;
  '/signup': typeof SignupRoute;
  '/signup-email': typeof SignupEmailRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/update-password': typeof UpdatePasswordRoute;
  '/$': typeof LayoutSplatRoute;
  '/': typeof LayoutIndexRoute;
  '/api/creative-chat': typeof ApiCreativeChatRoute;
  '/api/delete-user': typeof ApiDeleteUserRoute;
  '/api/fal-webhook': typeof ApiFalWebhookRoute;
  '/api/mesh': typeof ApiMeshRoute;
  '/api/parametric-chat': typeof ApiParametricChatRoute;
  '/api/title-generator': typeof ApiTitleGeneratorRoute;
  '/assets/$': typeof AssetsSplatRoute;
  '/app': typeof LayoutAuthAppRoute;
  '/history': typeof LayoutAuthHistoryRoute;
  '/settings': typeof LayoutAuthSettingsRoute;
  '/share/$id': typeof LayoutShareIdRoute;
  '/api/ai-settings/preferences': typeof ApiAiSettingsPreferencesRoute;
  '/api/ai-settings/profiles': typeof ApiAiSettingsProfilesRouteWithChildren;
  '/api/ai-settings/providers': typeof ApiAiSettingsProvidersRouteWithChildren;
  '/api/brep/evaluate': typeof ApiBrepEvaluateRoute;
  '/api/conversations/delete': typeof ApiConversationsDeleteRoute;
  '/api/conversations/workspace': typeof ApiConversationsWorkspaceRoute;
  '/api/export/step': typeof ApiExportStepRoute;
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute;
  '/api/models/catalog': typeof ApiModelsCatalogRouteWithChildren;
  '/api/opencode/models': typeof ApiOpencodeModelsRoute;
  '/api/scad-import/github': typeof ApiScadImportGithubRoute;
  '/api/settings/adminModels': typeof ApiSettingsAdminModelsRoute;
  '/api/settings/instanceIdentity': typeof ApiSettingsInstanceIdentityRoute;
  '/api/settings/runtimeIntegrations': typeof ApiSettingsRuntimeIntegrationsRoute;
  '/brep/$id': typeof LayoutAuthBrepIdRoute;
  '/editor/$id': typeof LayoutAuthEditorIdRoute;
  '/project/$id': typeof LayoutAuthProjectIdRoute;
  '/api/ai-settings/profiles/$profileId': typeof ApiAiSettingsProfilesProfileIdRoute;
  '/api/ai-settings/providers/$providerId': typeof ApiAiSettingsProvidersProviderIdRouteWithChildren;
  '/api/ai-settings/providers/builtins': typeof ApiAiSettingsProvidersBuiltinsRoute;
  '/api/ai-settings/providers/test': typeof ApiAiSettingsProvidersTestRoute;
  '/api/brep/export/grasshopper-plan': typeof ApiBrepExportGrasshopperPlanRoute;
  '/api/brep/export/step': typeof ApiBrepExportStepRoute;
  '/api/internal/account/delete': typeof ApiInternalAccountDeleteRoute;
  '/api/models/catalog/all': typeof ApiModelsCatalogAllRoute;
  '/brep': typeof LayoutAuthBrepIndexRoute;
  '/api/ai-settings/providers/$providerId/models': typeof ApiAiSettingsProvidersProviderIdModelsRouteWithChildren;
  '/api/ai-settings/providers/$providerId/models/$modelId': typeof ApiAiSettingsProvidersProviderIdModelsModelIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_layout': typeof LayoutRouteWithChildren;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/signin': typeof SigninRoute;
  '/signup': typeof SignupRoute;
  '/signup-email': typeof SignupEmailRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/update-password': typeof UpdatePasswordRoute;
  '/_layout/$': typeof LayoutSplatRoute;
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren;
  '/api/creative-chat': typeof ApiCreativeChatRoute;
  '/api/delete-user': typeof ApiDeleteUserRoute;
  '/api/fal-webhook': typeof ApiFalWebhookRoute;
  '/api/mesh': typeof ApiMeshRoute;
  '/api/parametric-chat': typeof ApiParametricChatRoute;
  '/api/title-generator': typeof ApiTitleGeneratorRoute;
  '/assets/$': typeof AssetsSplatRoute;
  '/_layout/': typeof LayoutIndexRoute;
  '/_layout/_auth/app': typeof LayoutAuthAppRoute;
  '/_layout/_auth/brep': typeof LayoutAuthBrepRouteWithChildren;
  '/_layout/_auth/history': typeof LayoutAuthHistoryRoute;
  '/_layout/_auth/settings': typeof LayoutAuthSettingsRoute;
  '/_layout/share/$id': typeof LayoutShareIdRoute;
  '/api/ai-settings/preferences': typeof ApiAiSettingsPreferencesRoute;
  '/api/ai-settings/profiles': typeof ApiAiSettingsProfilesRouteWithChildren;
  '/api/ai-settings/providers': typeof ApiAiSettingsProvidersRouteWithChildren;
  '/api/brep/evaluate': typeof ApiBrepEvaluateRoute;
  '/api/conversations/delete': typeof ApiConversationsDeleteRoute;
  '/api/conversations/workspace': typeof ApiConversationsWorkspaceRoute;
  '/api/export/step': typeof ApiExportStepRoute;
  '/api/jackson-pollock/$': typeof ApiJacksonPollockSplatRoute;
  '/api/models/catalog': typeof ApiModelsCatalogRouteWithChildren;
  '/api/opencode/models': typeof ApiOpencodeModelsRoute;
  '/api/scad-import/github': typeof ApiScadImportGithubRoute;
  '/api/settings/adminModels': typeof ApiSettingsAdminModelsRoute;
  '/api/settings/instanceIdentity': typeof ApiSettingsInstanceIdentityRoute;
  '/api/settings/runtimeIntegrations': typeof ApiSettingsRuntimeIntegrationsRoute;
  '/_layout/_auth/brep/$id': typeof LayoutAuthBrepIdRoute;
  '/_layout/_auth/editor/$id': typeof LayoutAuthEditorIdRoute;
  '/_layout/_auth/project/$id': typeof LayoutAuthProjectIdRoute;
  '/api/ai-settings/profiles/$profileId': typeof ApiAiSettingsProfilesProfileIdRoute;
  '/api/ai-settings/providers/$providerId': typeof ApiAiSettingsProvidersProviderIdRouteWithChildren;
  '/api/ai-settings/providers/builtins': typeof ApiAiSettingsProvidersBuiltinsRoute;
  '/api/ai-settings/providers/test': typeof ApiAiSettingsProvidersTestRoute;
  '/api/brep/export/grasshopper-plan': typeof ApiBrepExportGrasshopperPlanRoute;
  '/api/brep/export/step': typeof ApiBrepExportStepRoute;
  '/api/internal/account/delete': typeof ApiInternalAccountDeleteRoute;
  '/api/models/catalog/all': typeof ApiModelsCatalogAllRoute;
  '/_layout/_auth/brep/': typeof LayoutAuthBrepIndexRoute;
  '/api/ai-settings/providers/$providerId/models': typeof ApiAiSettingsProvidersProviderIdModelsRouteWithChildren;
  '/api/ai-settings/providers/$providerId/models/$modelId': typeof ApiAiSettingsProvidersProviderIdModelsModelIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/privacy-policy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/signup-email'
    | '/terms-of-service'
    | '/update-password'
    | '/$'
    | '/api/creative-chat'
    | '/api/delete-user'
    | '/api/fal-webhook'
    | '/api/mesh'
    | '/api/parametric-chat'
    | '/api/title-generator'
    | '/assets/$'
    | '/app'
    | '/brep'
    | '/history'
    | '/settings'
    | '/share/$id'
    | '/api/ai-settings/preferences'
    | '/api/ai-settings/profiles'
    | '/api/ai-settings/providers'
    | '/api/brep/evaluate'
    | '/api/conversations/delete'
    | '/api/conversations/workspace'
    | '/api/export/step'
    | '/api/jackson-pollock/$'
    | '/api/models/catalog'
    | '/api/opencode/models'
    | '/api/scad-import/github'
    | '/api/settings/adminModels'
    | '/api/settings/instanceIdentity'
    | '/api/settings/runtimeIntegrations'
    | '/brep/$id'
    | '/editor/$id'
    | '/project/$id'
    | '/api/ai-settings/profiles/$profileId'
    | '/api/ai-settings/providers/$providerId'
    | '/api/ai-settings/providers/builtins'
    | '/api/ai-settings/providers/test'
    | '/api/brep/export/grasshopper-plan'
    | '/api/brep/export/step'
    | '/api/internal/account/delete'
    | '/api/models/catalog/all'
    | '/brep/'
    | '/api/ai-settings/providers/$providerId/models'
    | '/api/ai-settings/providers/$providerId/models/$modelId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/confirm-email'
    | '/privacy-policy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/signup-email'
    | '/terms-of-service'
    | '/update-password'
    | '/$'
    | '/'
    | '/api/creative-chat'
    | '/api/delete-user'
    | '/api/fal-webhook'
    | '/api/mesh'
    | '/api/parametric-chat'
    | '/api/title-generator'
    | '/assets/$'
    | '/app'
    | '/history'
    | '/settings'
    | '/share/$id'
    | '/api/ai-settings/preferences'
    | '/api/ai-settings/profiles'
    | '/api/ai-settings/providers'
    | '/api/brep/evaluate'
    | '/api/conversations/delete'
    | '/api/conversations/workspace'
    | '/api/export/step'
    | '/api/jackson-pollock/$'
    | '/api/models/catalog'
    | '/api/opencode/models'
    | '/api/scad-import/github'
    | '/api/settings/adminModels'
    | '/api/settings/instanceIdentity'
    | '/api/settings/runtimeIntegrations'
    | '/brep/$id'
    | '/editor/$id'
    | '/project/$id'
    | '/api/ai-settings/profiles/$profileId'
    | '/api/ai-settings/providers/$providerId'
    | '/api/ai-settings/providers/builtins'
    | '/api/ai-settings/providers/test'
    | '/api/brep/export/grasshopper-plan'
    | '/api/brep/export/step'
    | '/api/internal/account/delete'
    | '/api/models/catalog/all'
    | '/brep'
    | '/api/ai-settings/providers/$providerId/models'
    | '/api/ai-settings/providers/$providerId/models/$modelId';
  id:
    | '__root__'
    | '/_layout'
    | '/confirm-email'
    | '/privacy-policy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/signup-email'
    | '/terms-of-service'
    | '/update-password'
    | '/_layout/$'
    | '/_layout/_auth'
    | '/api/creative-chat'
    | '/api/delete-user'
    | '/api/fal-webhook'
    | '/api/mesh'
    | '/api/parametric-chat'
    | '/api/title-generator'
    | '/assets/$'
    | '/_layout/'
    | '/_layout/_auth/app'
    | '/_layout/_auth/brep'
    | '/_layout/_auth/history'
    | '/_layout/_auth/settings'
    | '/_layout/share/$id'
    | '/api/ai-settings/preferences'
    | '/api/ai-settings/profiles'
    | '/api/ai-settings/providers'
    | '/api/brep/evaluate'
    | '/api/conversations/delete'
    | '/api/conversations/workspace'
    | '/api/export/step'
    | '/api/jackson-pollock/$'
    | '/api/models/catalog'
    | '/api/opencode/models'
    | '/api/scad-import/github'
    | '/api/settings/adminModels'
    | '/api/settings/instanceIdentity'
    | '/api/settings/runtimeIntegrations'
    | '/_layout/_auth/brep/$id'
    | '/_layout/_auth/editor/$id'
    | '/_layout/_auth/project/$id'
    | '/api/ai-settings/profiles/$profileId'
    | '/api/ai-settings/providers/$providerId'
    | '/api/ai-settings/providers/builtins'
    | '/api/ai-settings/providers/test'
    | '/api/brep/export/grasshopper-plan'
    | '/api/brep/export/step'
    | '/api/internal/account/delete'
    | '/api/models/catalog/all'
    | '/_layout/_auth/brep/'
    | '/api/ai-settings/providers/$providerId/models'
    | '/api/ai-settings/providers/$providerId/models/$modelId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren;
  ConfirmEmailRoute: typeof ConfirmEmailRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SigninRoute: typeof SigninRoute;
  SignupRoute: typeof SignupRoute;
  SignupEmailRoute: typeof SignupEmailRoute;
  TermsOfServiceRoute: typeof TermsOfServiceRoute;
  UpdatePasswordRoute: typeof UpdatePasswordRoute;
  ApiCreativeChatRoute: typeof ApiCreativeChatRoute;
  ApiDeleteUserRoute: typeof ApiDeleteUserRoute;
  ApiFalWebhookRoute: typeof ApiFalWebhookRoute;
  ApiMeshRoute: typeof ApiMeshRoute;
  ApiParametricChatRoute: typeof ApiParametricChatRoute;
  ApiTitleGeneratorRoute: typeof ApiTitleGeneratorRoute;
  AssetsSplatRoute: typeof AssetsSplatRoute;
  ApiAiSettingsPreferencesRoute: typeof ApiAiSettingsPreferencesRoute;
  ApiAiSettingsProfilesRoute: typeof ApiAiSettingsProfilesRouteWithChildren;
  ApiAiSettingsProvidersRoute: typeof ApiAiSettingsProvidersRouteWithChildren;
  ApiBrepEvaluateRoute: typeof ApiBrepEvaluateRoute;
  ApiConversationsDeleteRoute: typeof ApiConversationsDeleteRoute;
  ApiConversationsWorkspaceRoute: typeof ApiConversationsWorkspaceRoute;
  ApiExportStepRoute: typeof ApiExportStepRoute;
  ApiJacksonPollockSplatRoute: typeof ApiJacksonPollockSplatRoute;
  ApiModelsCatalogRoute: typeof ApiModelsCatalogRouteWithChildren;
  ApiOpencodeModelsRoute: typeof ApiOpencodeModelsRoute;
  ApiScadImportGithubRoute: typeof ApiScadImportGithubRoute;
  ApiSettingsAdminModelsRoute: typeof ApiSettingsAdminModelsRoute;
  ApiSettingsInstanceIdentityRoute: typeof ApiSettingsInstanceIdentityRoute;
  ApiSettingsRuntimeIntegrationsRoute: typeof ApiSettingsRuntimeIntegrationsRoute;
  ApiBrepExportGrasshopperPlanRoute: typeof ApiBrepExportGrasshopperPlanRoute;
  ApiBrepExportStepRoute: typeof ApiBrepExportStepRoute;
  ApiInternalAccountDeleteRoute: typeof ApiInternalAccountDeleteRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof LayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confirm-email': {
      id: '/confirm-email';
      path: '/confirm-email';
      fullPath: '/confirm-email';
      preLoaderRoute: typeof ConfirmEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy-policy': {
      id: '/privacy-policy';
      path: '/privacy-policy';
      fullPath: '/privacy-policy';
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/signin': {
      id: '/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/signup-email': {
      id: '/signup-email';
      path: '/signup-email';
      fullPath: '/signup-email';
      preLoaderRoute: typeof SignupEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/terms-of-service': {
      id: '/terms-of-service';
      path: '/terms-of-service';
      fullPath: '/terms-of-service';
      preLoaderRoute: typeof TermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/update-password': {
      id: '/update-password';
      path: '/update-password';
      fullPath: '/update-password';
      preLoaderRoute: typeof UpdatePasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof LayoutIndexRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/_layout/$': {
      id: '/_layout/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof LayoutSplatRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/_layout/_auth': {
      id: '/_layout/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof LayoutAuthRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/api/creative-chat': {
      id: '/api/creative-chat';
      path: '/api/creative-chat';
      fullPath: '/api/creative-chat';
      preLoaderRoute: typeof ApiCreativeChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/delete-user': {
      id: '/api/delete-user';
      path: '/api/delete-user';
      fullPath: '/api/delete-user';
      preLoaderRoute: typeof ApiDeleteUserRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/fal-webhook': {
      id: '/api/fal-webhook';
      path: '/api/fal-webhook';
      fullPath: '/api/fal-webhook';
      preLoaderRoute: typeof ApiFalWebhookRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/mesh': {
      id: '/api/mesh';
      path: '/api/mesh';
      fullPath: '/api/mesh';
      preLoaderRoute: typeof ApiMeshRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/parametric-chat': {
      id: '/api/parametric-chat';
      path: '/api/parametric-chat';
      fullPath: '/api/parametric-chat';
      preLoaderRoute: typeof ApiParametricChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/title-generator': {
      id: '/api/title-generator';
      path: '/api/title-generator';
      fullPath: '/api/title-generator';
      preLoaderRoute: typeof ApiTitleGeneratorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/assets/$': {
      id: '/assets/$';
      path: '/assets/$';
      fullPath: '/assets/$';
      preLoaderRoute: typeof AssetsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/_auth/app': {
      id: '/_layout/_auth/app';
      path: '/app';
      fullPath: '/app';
      preLoaderRoute: typeof LayoutAuthAppRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/_auth/brep': {
      id: '/_layout/_auth/brep';
      path: '/brep';
      fullPath: '/brep';
      preLoaderRoute: typeof LayoutAuthBrepRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/_auth/history': {
      id: '/_layout/_auth/history';
      path: '/history';
      fullPath: '/history';
      preLoaderRoute: typeof LayoutAuthHistoryRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/_auth/settings': {
      id: '/_layout/_auth/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof LayoutAuthSettingsRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/share/$id': {
      id: '/_layout/share/$id';
      path: '/share/$id';
      fullPath: '/share/$id';
      preLoaderRoute: typeof LayoutShareIdRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    '/api/ai-settings/preferences': {
      id: '/api/ai-settings/preferences';
      path: '/api/ai-settings/preferences';
      fullPath: '/api/ai-settings/preferences';
      preLoaderRoute: typeof ApiAiSettingsPreferencesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/ai-settings/profiles': {
      id: '/api/ai-settings/profiles';
      path: '/api/ai-settings/profiles';
      fullPath: '/api/ai-settings/profiles';
      preLoaderRoute: typeof ApiAiSettingsProfilesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/ai-settings/providers': {
      id: '/api/ai-settings/providers';
      path: '/api/ai-settings/providers';
      fullPath: '/api/ai-settings/providers';
      preLoaderRoute: typeof ApiAiSettingsProvidersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/brep/evaluate': {
      id: '/api/brep/evaluate';
      path: '/api/brep/evaluate';
      fullPath: '/api/brep/evaluate';
      preLoaderRoute: typeof ApiBrepEvaluateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/conversations/delete': {
      id: '/api/conversations/delete';
      path: '/api/conversations/delete';
      fullPath: '/api/conversations/delete';
      preLoaderRoute: typeof ApiConversationsDeleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/conversations/workspace': {
      id: '/api/conversations/workspace';
      path: '/api/conversations/workspace';
      fullPath: '/api/conversations/workspace';
      preLoaderRoute: typeof ApiConversationsWorkspaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/export/step': {
      id: '/api/export/step';
      path: '/api/export/step';
      fullPath: '/api/export/step';
      preLoaderRoute: typeof ApiExportStepRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/jackson-pollock/$': {
      id: '/api/jackson-pollock/$';
      path: '/api/jackson-pollock/$';
      fullPath: '/api/jackson-pollock/$';
      preLoaderRoute: typeof ApiJacksonPollockSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/models/catalog': {
      id: '/api/models/catalog';
      path: '/api/models/catalog';
      fullPath: '/api/models/catalog';
      preLoaderRoute: typeof ApiModelsCatalogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/opencode/models': {
      id: '/api/opencode/models';
      path: '/api/opencode/models';
      fullPath: '/api/opencode/models';
      preLoaderRoute: typeof ApiOpencodeModelsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/scad-import/github': {
      id: '/api/scad-import/github';
      path: '/api/scad-import/github';
      fullPath: '/api/scad-import/github';
      preLoaderRoute: typeof ApiScadImportGithubRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/settings/adminModels': {
      id: '/api/settings/adminModels';
      path: '/api/settings/adminModels';
      fullPath: '/api/settings/adminModels';
      preLoaderRoute: typeof ApiSettingsAdminModelsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/settings/instanceIdentity': {
      id: '/api/settings/instanceIdentity';
      path: '/api/settings/instanceIdentity';
      fullPath: '/api/settings/instanceIdentity';
      preLoaderRoute: typeof ApiSettingsInstanceIdentityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/settings/runtimeIntegrations': {
      id: '/api/settings/runtimeIntegrations';
      path: '/api/settings/runtimeIntegrations';
      fullPath: '/api/settings/runtimeIntegrations';
      preLoaderRoute: typeof ApiSettingsRuntimeIntegrationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/_auth/brep/': {
      id: '/_layout/_auth/brep/';
      path: '/';
      fullPath: '/brep/';
      preLoaderRoute: typeof LayoutAuthBrepIndexRouteImport;
      parentRoute: typeof LayoutAuthBrepRoute;
    };
    '/_layout/_auth/brep/$id': {
      id: '/_layout/_auth/brep/$id';
      path: '/$id';
      fullPath: '/brep/$id';
      preLoaderRoute: typeof LayoutAuthBrepIdRouteImport;
      parentRoute: typeof LayoutAuthBrepRoute;
    };
    '/_layout/_auth/editor/$id': {
      id: '/_layout/_auth/editor/$id';
      path: '/editor/$id';
      fullPath: '/editor/$id';
      preLoaderRoute: typeof LayoutAuthEditorIdRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/_layout/_auth/project/$id': {
      id: '/_layout/_auth/project/$id';
      path: '/project/$id';
      fullPath: '/project/$id';
      preLoaderRoute: typeof LayoutAuthProjectIdRouteImport;
      parentRoute: typeof LayoutAuthRoute;
    };
    '/api/ai-settings/profiles/$profileId': {
      id: '/api/ai-settings/profiles/$profileId';
      path: '/$profileId';
      fullPath: '/api/ai-settings/profiles/$profileId';
      preLoaderRoute: typeof ApiAiSettingsProfilesProfileIdRouteImport;
      parentRoute: typeof ApiAiSettingsProfilesRoute;
    };
    '/api/ai-settings/providers/$providerId': {
      id: '/api/ai-settings/providers/$providerId';
      path: '/$providerId';
      fullPath: '/api/ai-settings/providers/$providerId';
      preLoaderRoute: typeof ApiAiSettingsProvidersProviderIdRouteImport;
      parentRoute: typeof ApiAiSettingsProvidersRoute;
    };
    '/api/ai-settings/providers/builtins': {
      id: '/api/ai-settings/providers/builtins';
      path: '/builtins';
      fullPath: '/api/ai-settings/providers/builtins';
      preLoaderRoute: typeof ApiAiSettingsProvidersBuiltinsRouteImport;
      parentRoute: typeof ApiAiSettingsProvidersRoute;
    };
    '/api/ai-settings/providers/test': {
      id: '/api/ai-settings/providers/test';
      path: '/test';
      fullPath: '/api/ai-settings/providers/test';
      preLoaderRoute: typeof ApiAiSettingsProvidersTestRouteImport;
      parentRoute: typeof ApiAiSettingsProvidersRoute;
    };
    '/api/brep/export/grasshopper-plan': {
      id: '/api/brep/export/grasshopper-plan';
      path: '/api/brep/export/grasshopper-plan';
      fullPath: '/api/brep/export/grasshopper-plan';
      preLoaderRoute: typeof ApiBrepExportGrasshopperPlanRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/brep/export/step': {
      id: '/api/brep/export/step';
      path: '/api/brep/export/step';
      fullPath: '/api/brep/export/step';
      preLoaderRoute: typeof ApiBrepExportStepRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/internal/account/delete': {
      id: '/api/internal/account/delete';
      path: '/api/internal/account/delete';
      fullPath: '/api/internal/account/delete';
      preLoaderRoute: typeof ApiInternalAccountDeleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/models/catalog/all': {
      id: '/api/models/catalog/all';
      path: '/all';
      fullPath: '/api/models/catalog/all';
      preLoaderRoute: typeof ApiModelsCatalogAllRouteImport;
      parentRoute: typeof ApiModelsCatalogRoute;
    };
    '/api/ai-settings/providers/$providerId/models': {
      id: '/api/ai-settings/providers/$providerId/models';
      path: '/models';
      fullPath: '/api/ai-settings/providers/$providerId/models';
      preLoaderRoute: typeof ApiAiSettingsProvidersProviderIdModelsRouteImport;
      parentRoute: typeof ApiAiSettingsProvidersProviderIdRoute;
    };
    '/api/ai-settings/providers/$providerId/models/$modelId': {
      id: '/api/ai-settings/providers/$providerId/models/$modelId';
      path: '/$modelId';
      fullPath: '/api/ai-settings/providers/$providerId/models/$modelId';
      preLoaderRoute: typeof ApiAiSettingsProvidersProviderIdModelsModelIdRouteImport;
      parentRoute: typeof ApiAiSettingsProvidersProviderIdModelsRoute;
    };
  }
}

interface LayoutAuthBrepRouteChildren {
  LayoutAuthBrepIdRoute: typeof LayoutAuthBrepIdRoute;
  LayoutAuthBrepIndexRoute: typeof LayoutAuthBrepIndexRoute;
}

const LayoutAuthBrepRouteChildren: LayoutAuthBrepRouteChildren = {
  LayoutAuthBrepIdRoute: LayoutAuthBrepIdRoute,
  LayoutAuthBrepIndexRoute: LayoutAuthBrepIndexRoute,
};

const LayoutAuthBrepRouteWithChildren = LayoutAuthBrepRoute._addFileChildren(
  LayoutAuthBrepRouteChildren,
);

interface LayoutAuthRouteChildren {
  LayoutAuthAppRoute: typeof LayoutAuthAppRoute;
  LayoutAuthBrepRoute: typeof LayoutAuthBrepRouteWithChildren;
  LayoutAuthHistoryRoute: typeof LayoutAuthHistoryRoute;
  LayoutAuthSettingsRoute: typeof LayoutAuthSettingsRoute;
  LayoutAuthEditorIdRoute: typeof LayoutAuthEditorIdRoute;
  LayoutAuthProjectIdRoute: typeof LayoutAuthProjectIdRoute;
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthAppRoute: LayoutAuthAppRoute,
  LayoutAuthBrepRoute: LayoutAuthBrepRouteWithChildren,
  LayoutAuthHistoryRoute: LayoutAuthHistoryRoute,
  LayoutAuthSettingsRoute: LayoutAuthSettingsRoute,
  LayoutAuthEditorIdRoute: LayoutAuthEditorIdRoute,
  LayoutAuthProjectIdRoute: LayoutAuthProjectIdRoute,
};

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
);

interface LayoutRouteChildren {
  LayoutSplatRoute: typeof LayoutSplatRoute;
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren;
  LayoutIndexRoute: typeof LayoutIndexRoute;
  LayoutShareIdRoute: typeof LayoutShareIdRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSplatRoute: LayoutSplatRoute,
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutShareIdRoute: LayoutShareIdRoute,
};

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren);

interface ApiAiSettingsProfilesRouteChildren {
  ApiAiSettingsProfilesProfileIdRoute: typeof ApiAiSettingsProfilesProfileIdRoute;
}

const ApiAiSettingsProfilesRouteChildren: ApiAiSettingsProfilesRouteChildren = {
  ApiAiSettingsProfilesProfileIdRoute: ApiAiSettingsProfilesProfileIdRoute,
};

const ApiAiSettingsProfilesRouteWithChildren =
  ApiAiSettingsProfilesRoute._addFileChildren(
    ApiAiSettingsProfilesRouteChildren,
  );

interface ApiAiSettingsProvidersProviderIdModelsRouteChildren {
  ApiAiSettingsProvidersProviderIdModelsModelIdRoute: typeof ApiAiSettingsProvidersProviderIdModelsModelIdRoute;
}

const ApiAiSettingsProvidersProviderIdModelsRouteChildren: ApiAiSettingsProvidersProviderIdModelsRouteChildren =
  {
    ApiAiSettingsProvidersProviderIdModelsModelIdRoute:
      ApiAiSettingsProvidersProviderIdModelsModelIdRoute,
  };

const ApiAiSettingsProvidersProviderIdModelsRouteWithChildren =
  ApiAiSettingsProvidersProviderIdModelsRoute._addFileChildren(
    ApiAiSettingsProvidersProviderIdModelsRouteChildren,
  );

interface ApiAiSettingsProvidersProviderIdRouteChildren {
  ApiAiSettingsProvidersProviderIdModelsRoute: typeof ApiAiSettingsProvidersProviderIdModelsRouteWithChildren;
}

const ApiAiSettingsProvidersProviderIdRouteChildren: ApiAiSettingsProvidersProviderIdRouteChildren =
  {
    ApiAiSettingsProvidersProviderIdModelsRoute:
      ApiAiSettingsProvidersProviderIdModelsRouteWithChildren,
  };

const ApiAiSettingsProvidersProviderIdRouteWithChildren =
  ApiAiSettingsProvidersProviderIdRoute._addFileChildren(
    ApiAiSettingsProvidersProviderIdRouteChildren,
  );

interface ApiAiSettingsProvidersRouteChildren {
  ApiAiSettingsProvidersProviderIdRoute: typeof ApiAiSettingsProvidersProviderIdRouteWithChildren;
  ApiAiSettingsProvidersBuiltinsRoute: typeof ApiAiSettingsProvidersBuiltinsRoute;
  ApiAiSettingsProvidersTestRoute: typeof ApiAiSettingsProvidersTestRoute;
}

const ApiAiSettingsProvidersRouteChildren: ApiAiSettingsProvidersRouteChildren =
  {
    ApiAiSettingsProvidersProviderIdRoute:
      ApiAiSettingsProvidersProviderIdRouteWithChildren,
    ApiAiSettingsProvidersBuiltinsRoute: ApiAiSettingsProvidersBuiltinsRoute,
    ApiAiSettingsProvidersTestRoute: ApiAiSettingsProvidersTestRoute,
  };

const ApiAiSettingsProvidersRouteWithChildren =
  ApiAiSettingsProvidersRoute._addFileChildren(
    ApiAiSettingsProvidersRouteChildren,
  );

interface ApiModelsCatalogRouteChildren {
  ApiModelsCatalogAllRoute: typeof ApiModelsCatalogAllRoute;
}

const ApiModelsCatalogRouteChildren: ApiModelsCatalogRouteChildren = {
  ApiModelsCatalogAllRoute: ApiModelsCatalogAllRoute,
};

const ApiModelsCatalogRouteWithChildren =
  ApiModelsCatalogRoute._addFileChildren(ApiModelsCatalogRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SignupEmailRoute: SignupEmailRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ApiCreativeChatRoute: ApiCreativeChatRoute,
  ApiDeleteUserRoute: ApiDeleteUserRoute,
  ApiFalWebhookRoute: ApiFalWebhookRoute,
  ApiMeshRoute: ApiMeshRoute,
  ApiParametricChatRoute: ApiParametricChatRoute,
  ApiTitleGeneratorRoute: ApiTitleGeneratorRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  ApiAiSettingsPreferencesRoute: ApiAiSettingsPreferencesRoute,
  ApiAiSettingsProfilesRoute: ApiAiSettingsProfilesRouteWithChildren,
  ApiAiSettingsProvidersRoute: ApiAiSettingsProvidersRouteWithChildren,
  ApiBrepEvaluateRoute: ApiBrepEvaluateRoute,
  ApiConversationsDeleteRoute: ApiConversationsDeleteRoute,
  ApiConversationsWorkspaceRoute: ApiConversationsWorkspaceRoute,
  ApiExportStepRoute: ApiExportStepRoute,
  ApiJacksonPollockSplatRoute: ApiJacksonPollockSplatRoute,
  ApiModelsCatalogRoute: ApiModelsCatalogRouteWithChildren,
  ApiOpencodeModelsRoute: ApiOpencodeModelsRoute,
  ApiScadImportGithubRoute: ApiScadImportGithubRoute,
  ApiSettingsAdminModelsRoute: ApiSettingsAdminModelsRoute,
  ApiSettingsInstanceIdentityRoute: ApiSettingsInstanceIdentityRoute,
  ApiSettingsRuntimeIntegrationsRoute: ApiSettingsRuntimeIntegrationsRoute,
  ApiBrepExportGrasshopperPlanRoute: ApiBrepExportGrasshopperPlanRoute,
  ApiBrepExportStepRoute: ApiBrepExportStepRoute,
  ApiInternalAccountDeleteRoute: ApiInternalAccountDeleteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
